---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[jenkins_wrapper::default]
      - recipe[jenkins_wrapper::plugins]
      - recipe[jenkins_wrapper::creds]
      - recipe[jenkins_wrapper::folder]
      - recipe[jenkins_wrapper::jobs]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
